# Generated by Django 2.2.5 on 2019-09-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comisaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('long', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'verbose_name': 'Comisaria',
                'verbose_name_plural': 'Comisarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Denunciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
            options={
                'verbose_name': 'Denunciante',
                'verbose_name_plural': 'Denunciantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('1', 'simple'), ('2', 'Agravado')], max_length=1)),
                ('objeto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('long', models.DecimalField(decimal_places=8, max_digits=10)),
                ('estado', models.CharField(choices=[('1', 'Abierta'), ('2', 'Pend. Verificacion'), ('3', 'Rechazada')], max_length=1)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.Denunciante')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'managed': True,
            },
        ),
    ]
