# Generated by Django 2.2.5 on 2019-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Denunciante',
            new_name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='denunciante',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='objeto',
        ),
        migrations.AlterField(
            model_name='comisaria',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comisaria',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('1', 'Pend. Verificacion'), ('2', 'Aceptada'), ('3', 'Rechazada')], max_length=1),
        ),
    ]
